### ISSUE TITLE
Pre-delete errands are displayed by ops manager

### ISSUE THREAD

**Issue by glyn** [pivotal-cf/docs-partners#2]
According to https://github.com/pivotal-cf/docs-partners/blob/master/lifecycle-errands.html.md.erb#L24, "Ops Manager does not display pre-delete errands, and an operator cannot prevent them from running." However, on ops manager 1.7.9, I can see a pre-delete errand in the MySQL tile, so presumably this restriction has been lifted.

**Comment by bentarnoff** [comment]
Hey @glyn, thanks for bringing this to our attention. The documentation is incorrect on that point. Ops Manager has a checklist of errands that you can optionally uncheck if you don't want them to run on the next "Apply Changes." If your pending change is to delete, you will see the pre-delete errands. I'll correct the documentation. 

I'm closing this issue for now but please feel free to be in touch with further feedback. Thanks!

**Comment by glyn** [comment]
Thanks @bentarnoff. Please note that the pre-delete errands are visible even if there is no pending  deletion.

I would also like politely to question the process of closing an issue before it has been addressed. In this particular case, I'm not fussy, but suppose I wanted to know when the correction was published so I could read it? I would suggest that you consider keeping issues open until the solution is visible to the raiser. This will encourage outside contributors by keeping them in the loop when they raise issues. Remember that outside contributors are very valuable and need all the encouragement we can give them. Perhaps you might like to bring this up at your next retro?

**Comment by bentarnoff** [comment]
Thanks for the feedback, @glyn. I am re-opening the issue. You can view the new changes at the Github repo (https://github.com/pivotal-cf/docs-partners/blob/master/lifecycle-errands.html.md.erb) or at our staging site (http://docs-pcf-staging.cfapps.io/partners/lifecycle-errands.html). Please let me know if these changes resolve your concerns. 

In the future, if you have a specific change you'd like to see reflected in the documentation, please submit a PR.

Thanks for your help.

**Comment by glyn** [comment]
Thanks so much @bentarnoff! Those edits look great. I'm happy to submit a PR in future in cases where I know what the change should be.
